name: hellow-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hellow-world.txt)"
